theme: minimal-mistakes-jekyll

locale: zh-CN
timezone: Asia/Shanghai

title: 张爱宇
name: 张爱宇
description: "个人博客 | 记录技术与生活"
url: "https://zhangaiyu1996.github.io"
baseurl: ""

author:
  name: 张爱宇
  email: 770983009@qq.com
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zhangaiyu1996"

permalink: /:categories/:title/

paginate: 10
paginate_path: /page:num/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      toc_sticky: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

include:
  - _pages

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
